Feat/location detail view
technologiestiftung/kulturdaten-webapp pull request #30
Opened 2023-11-14 13:17 UTC by ThorstenDiekhof

Ich probiere mal einen Draft pull request. 

Bitte drüber schauen und checken, ob ich die richtige Richtung eingeschlagen habe.

2023-11-14 17:36 UTC, herrherrmann requested changes
Supercooler und konsistenter Anfang! 👏 

Habe noch nicht 100% durchgeschaut, aber hier sind schon mal ein paar Hinweise, u.a. bezüglich des Routen-Setups. ✌️

2023-11-14 17:36 UTC, herrherrmann commented on src/components/LocationEditor/service.ts
> +}
Genau die gleiche Funktion haben wir jetzt zwei mal. Wir könnten also überlegen, diese (z.B. nach `utils/content`) auszulagern! 💡

2023-11-14 17:36 UTC, herrherrmann commented on src/components/LocationEditor/service.ts
> +// TODO: adapt to locations
Dieses `TODO` ist eigentlich schon erledigt, oder?

2023-11-14 17:36 UTC, herrherrmann commented on src/pages/admin/locations/create.tsx
> +export const getServerSideProps: GetServerSideProps<Props> = async (context) => ({
Hier sollten wir (analog zu `src/pages/admin/attractions/create.tsx`) auch die Wrapper-Funktion `withApiClientAndPagination` verwenden. Die sorgt auch dafür, dass der Access Token validiert und ggf. zum Login umgeleitet wird! (Denn diese Route soll ja auch nur für eingeloggte Benutzer:innen erreichbar sein.)

2023-11-14 17:36 UTC, herrherrmann commented on src/pages/admin/locations/[identifier].tsx
> +export const getServerSideProps: GetServerSideProps<Props> = async (context) => {
Gleicher Kommentar wie bei der `/create`-Route: Hier sollten wir (analog zu `src/pages/admin/attractions/[identifier].tsx`) auch die Wrapper-Funktion `withApiClientAndPagination` verwenden. Dann wird der Code unten auch etwas kürzer, weil uns die Funktion die Variablen `apiClient` und `accessToken` vorbereitet. 🚀

2023-11-14 17:37 UTC, herrherrmann commented on src/pages/admin/locations/create.tsx
> +export const getServerSideProps: GetServerSideProps<Props> = async (context) => ({
**Update:** Habe gerade gemerkt, dass sich das Format der `withApiClientAndPagination`-Funktion nochmal ein bisschen in https://github.com/technologiestiftung/kulturdaten-webapp/pull/29 ändert! Nur als Hinweis. ✌️

2023-11-15 07:52 UTC, ThorstenDiekhof commented on src/components/LocationEditor/service.ts
> +// TODO: adapt to locations
Hier wollte ich mehr Daten aus der Location rausholen. Das kann aber auch Teil einer weiteren Story sein. Sollten uns mal überlegen, wie wir mit z.B. "manager" oder so umgehen. Was genau angezeigt wird usw.

2023-11-15 09:08 UTC, herrherrmann reviewed
Der Page-/Form-Teil sieht auch super aus! Nur eine kleine Anmerkung zu den verwendeten HTML-Elementen.

Das Feld "Typ des Ortes - Physischer Ort oder Virtueller Ort" aus dem Ticket fehlt noch, oder?

2023-11-15 09:08 UTC, herrherrmann commented on src/components/AddressFormFields/index.tsx
> +	gap: spacings.get(2),
Diese CSS-Properties würden nur im Zusammenhang mit `display: flex` funktionieren. Ist wahrscheinlich einfach nach einem Copy & Paste übrig geblieben, oder? :D Jedenfalls können die einfach weg.

2023-11-15 09:08 UTC, herrherrmann commented on src/components/AddressFormFields/index.tsx
> +				required={true}
Die ersten drei Address-Felder sind jetzt erforderlich, obwohl sie rein technisch nicht von der API verlangt werden, oder? Ich find’s aber sinnvoll so!

2023-11-15 13:01 UTC, ThorstenDiekhof commented on src/components/AddressFormFields/index.tsx
> +const Label = styled.label({});
Super Sache das. Genau das habe ich gesucht. Finde die Einrahmung gar nicht schlecht.... ich denke hier brauchen wir mal ein Konzept. Würde gerne viele Dinge in den großen Datenmodellen zusammenfassen - mit eigener Bezeichnung und abgesetzt.
Erstmal aber einfach border und padding raus.

2023-11-15 13:02 UTC, ThorstenDiekhof commented on src/components/AddressFormFields/index.tsx
> +	gap: spacings.get(2),
Wollte keinen "Default"-Style durcheinanderbringen.. aber klar, mit rausgenommenem Flex bringt das hier nichts.

2023-11-15 13:04 UTC, ThorstenDiekhof commented on src/components/AddressFormFields/index.tsx
> +				required={true}
mhmm... jetzt wo du es sagst habe ich es erstmal parallel zum Datenmodell gehalten... und das required herausgenommen. 
Hier brauchen wir unbedingt eine Kennzeichnung für den Nutzer der Felder, die required sind.

2023-11-15 13:06 UTC, ThorstenDiekhof commented
"Das Feld "Typ des Ortes - Physischer Ort oder Virtueller Ort" aus dem Ticket fehlt noch, oder?"

Ist absichtlich nicht mit diesem Branch umgesetzt worden. Das erfordert Anpassungen an der API und dem Datenmodell. Das würde ich gerne unabhängig davon umsetzen.

2023-11-15 13:31 UTC, herrherrmann approved these changes
Abgesehen von der Linter-Warnung ist jetzt alles top! 👍

2023-11-15 13:31 UTC, herrherrmann commented on src/components/LocationEditor/service.ts
> +
Hier gibt’s noch eine Linter-Warnung wegen der doppelten Leerzeichen!

2023-11-15 14:33 UTC, merged